wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: cyan
      normal: gray
  refreshInterval: 1
  mods:
    todo:
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 0
        left: 0
        height: 2
        width: 1
      refreshInterval: 15s

    textfile:
      title: "Notes"
      enabled: true
      filePaths:
      - "~/.config/wtf/notes.txt"
      format: true
      formatStyle: "dracula"
      position:
        top: 2
        left: 0
        height: 2
        width: 1
      refreshInterval: 15s
      wrapText: true

    gcal:
      colors:
        title: "green"
        eventTime: "lightblue"
        description: "yellow"
        highlights:
        - ['1on1|1\/11', 'green']
        - ['apple|google|aws', 'blue']
        - ['interview|meet', 'magenta']
        - ['lunch', 'yellow']
        past: "gray"
      calendarReadLevel: "reader"
      conflictIcon: "🛑"
      currentIcon: "🟢"
      displayResponseStatus: true
      email: "nathanssfirmo@gmail.com"
      enabled: true
      eventCount: 15
      hourFormat: "24"
      multiCalendar: true
      position:
        top: 4
        left: 0
        height: 5
        width: 1
      refreshInterval: 5m
      secretFile: "~/.config/wtf/gcal/client_secret.json"
      showDeclined: true
      showEndTime: false
      timezone: "America/Sao_Paulo"
      withLocation: true

    unhealthyPods:
      type: "cmdrunner"
      title: "Unhealthy pods"
      cmd: "/home/nathan/.config/wtf/scripts/unhealthy-pods.sh"
      enabled: true
      position:
        top: 0
        left: 1
        height: 3
        width: 2
      refreshInterval: 5s

    kubectlStatus:
      type: "cmdrunner"
      title: "K8s Icv Deployments"
      cmd: "/home/nathan/.config/wtf/scripts/k8s.sh"
      enabled: true
      position:
        top: 3
        left: 1
        height: 6
        width: 2
      refreshInterval: 5s

    actionsStatus:
      type: "cmdrunner"
      title: "GH Actions"
      cmd: "/home/nathan/.config/wtf/scripts/gh.sh"
      enabled: true
      position:
        top: 2
        left: 3
        height: 2
        width: 1
      refreshInterval: 5s

    urlCheck:
      type: "cmdrunner"
      title: "Services Status"
      cmd: "/home/nathan/.config/wtf/scripts/services-status.sh"
      enabled: true
      position:
        top: 4
        left: 3
        height: 2
        width: 1
      refreshInterval: 10s

    docker:
      title: "Docker Usage"
      type: "cmdrunner"
      cmd: "/home/nathan/.config/wtf/scripts/docker.sh"
      enabled: true
      position:
        top: 0
        left: 3
        height: 2
        width: 1
      refreshInterval: 5s

    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 6
        left: 3
        height: 3
        width: 1
      refreshInterval: 1s
      showCPU: true
      showMem: true
      showSwp: true
