theme = "catppuccin_mocha"

[editor]
auto-save = true
auto-format = true
idle-timeout = 0

[editor.statusline]
left = ["version-control", "file-name"]
right = ["diagnostics", "mode"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
C-h = "jump_view_left" 
C-j = "jump_view_down"
C-k = "jump_view_up" 
C-l = "jump_view_right"
C-s = [":format", ":write-all!"]
C-q = ":bclose"

[keys.normal.t]
t = ":quit-all!" 

[keys.insert.j]
j = "normal_mode" 

[keys.normal.q]
q = "vsplit"
d = "wclose"

[keys.insert]
C-space = "completion"
C-v = ["paste_clipboard_after", "collapse_selection"]

